# Generated by Django 3.1.2 on 2021-11-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_object_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.RemoveField(
            model_name='object',
            name='article',
        ),
    ]
