# Generated by Django 3.1.2 on 2021-11-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211106_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Scope',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='object',
            new_name='scope',
        ),
    ]
