# Generated by Django 3.1.2 on 2021-11-06 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20211106_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='scope',
        ),
        migrations.AddField(
            model_name='relationship',
            name='scopes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.scope', verbose_name='Теги'),
        ),
    ]
